/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class marshal_magicbookapp_Detector_DetectTimerTask */

#ifndef _Included_marshal_magicbookapp_Detector_DetectTimerTask
#define _Included_marshal_magicbookapp_Detector_DetectTimerTask
#ifdef __cplusplus
extern "C" {
#endif
#undef marshal_magicbookapp_Detector_DetectTimerTask_VIRGIN
#define marshal_magicbookapp_Detector_DetectTimerTask_VIRGIN 0L
#undef marshal_magicbookapp_Detector_DetectTimerTask_SCHEDULED
#define marshal_magicbookapp_Detector_DetectTimerTask_SCHEDULED 1L
#undef marshal_magicbookapp_Detector_DetectTimerTask_EXECUTED
#define marshal_magicbookapp_Detector_DetectTimerTask_EXECUTED 2L
#undef marshal_magicbookapp_Detector_DetectTimerTask_CANCELLED
#define marshal_magicbookapp_Detector_DetectTimerTask_CANCELLED 3L
#ifdef __cplusplus
}
#endif
#endif
