/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class marshal_magicbookapp_Detector_LooperThread */

#ifndef _Included_marshal_magicbookapp_Detector_LooperThread
#define _Included_marshal_magicbookapp_Detector_LooperThread
#ifdef __cplusplus
extern "C" {
#endif
#undef marshal_magicbookapp_Detector_LooperThread_MIN_PRIORITY
#define marshal_magicbookapp_Detector_LooperThread_MIN_PRIORITY 1L
#undef marshal_magicbookapp_Detector_LooperThread_NORM_PRIORITY
#define marshal_magicbookapp_Detector_LooperThread_NORM_PRIORITY 5L
#undef marshal_magicbookapp_Detector_LooperThread_MAX_PRIORITY
#define marshal_magicbookapp_Detector_LooperThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
